@RestaurantsAPI_HostAddress = https://localhost:7158
//http://localhost:5220
@token = CfDJ8JdJEervLchDnMkfpUArbPtqsXKnWVoY2QLyE7FMeZH4P0rRnKV_DM1FRXztusIXTrDDq6ODuB97hJoGvxttiCtMMyjJyXXtRiIjAuthCjM5dPzF8tveGYx_U87TWtZfQp8dmkaCCK51tr3Gx-c-iG95sVHfyMxqgw6wkxjFkILopgI26qDkzx2NKqiuuyCecWZ2r9ZaCnFdUH9cVys2PTD-Vnl1CrirUQ2mY5O0A6q3HoL4pXZGKgJHZaWeOqP-Ts21BAjp0AGi6NkedETFyzOWQrcejEJtURkm2xMvinT-mZIFZd1OVeHhAiF8ma4w6Z77MkJzWfVXMZbfiFN6GjrhzMJElDoK_Lt3_NyU1bEtMTRzyZ8c8Dn5DbotlIEP00GTgX1kwy6R0kEky_n0YD98d035oVY3Qobaa7Dqo6c_AZWVyAoydQy1six1ZOTCJkfGvmTW21-_LX0yHIkAkEepUyo1ormBkXJmazM1iYhHAw1cqQ-XPn1v0H3YdWfzVJsPtadV0cpL7xe49EQ6Yjxzn4ezOrpXOnAvQ9KAgRCE4tPoqJgjPofKNY2DJ-kYOQYAkmrX_jzOZWJ0RlJhh62GQL2tRyrkncV9L186DQZBf4McYTfXewdeSmwWJNaP3fB1WtlXfAJRyTPN65mP2ia5tG2SfAi-bD2ihuYb1Lskxs0lAIKR4MFiXEjsgIrp-VGx5jcZ4vuimG-ycLRztXygMiuYhaKJx0_U3BR1kBgXjALJF_5R-7lwReAWfJGVCynIrdhslW4zNXYpejYSNndkDmhoM1v44CmVcqeJbmfyb6W78TOx0EqFxlE9e0CxYVDqKot2eKuoNfqtBKlrsVg

GET {{RestaurantsAPI_HostAddress}}/api/restaurants?searchPhrase=&pageSize=3&pageIndex=1&sortBy=Name&sortDirection=Descending
Authorization: Bearer {{token}}
###
GET {{RestaurantsAPI_HostAddress}}/api/restaurants/11
Authorization: Bearer {{token}}

###
GET {{RestaurantsAPI_HostAddress}}/api/restaurants/3
Authorization:Bearer{{token}}

###
GET {{RestaurantsAPI_HostAddress}}/api/restaurants/123

###
POST {{RestaurantsAPI_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "Name": "Owner Restaurant2",
  "Description": "A cozy restaurant serving a variety of delicious dishes.",
  "Category": "Indian",
  "HasDelivery": true,
  "ContactEmail": "info@tast.com",
  "ContactNumber": "555-1234",
  "City": "New York",
  "Street": "123 Main Street",
  "PostalCode": "10-010"
}
###

DELETE {{RestaurantsAPI_HostAddress}}/api/restaurants/11
Authorization: Bearer {{token}}
###

PATCH {{RestaurantsAPI_HostAddress}}/api/restaurants/13
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "Name": "Updated restaurant",
  "Description": "This is a sample restaurant description.",
  "HasDelivery": true
}
###





POST {{RestaurantsAPI_HostAddress}}/api/restaurants/7/dishes
Content-Type: application/json
{
  "Name": "Spaghetti Bolognese",
  "Description": "Classic Italian pasta dish with rich meat sauce",
  "Price": 12.99,
  "KiloCalories": 750
}
###

GET {{RestaurantsAPI_HostAddress}}/api/restaurants/3/dishes
Authorization: Bearer {{token}}
###

GET {{RestaurantsAPI_HostAddress}}/api/restaurants/3/dishes/3
###
DELETE {{RestaurantsAPI_HostAddress}}/api/restaurants/4/dishes
###






POST {{RestaurantsAPI_HostAddress}}/api/identity/register
Content-Type: application/json
{
    "email": "owner2@test.com",
    "password": "Password1!"
}
###
POST {{RestaurantsAPI_HostAddress}}/api/identity/login
Content-Type: application/json
{
    "email": "owner2@test.com",
    "password": "Password1!"
}
###

PATCH {{RestaurantsAPI_HostAddress}}/api/identity/user
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "Nationality": "French",
  "DateOfBirth": "2010-01-01"
}
###
POST {{RestaurantsAPI_HostAddress}}/api/identity/userRole
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "UserEmail": "owner2@test.com",
  "RoleName": "Owner"
}
###