@RestaurantsAPI_HostAddress = https://localhost:7158
//http://localhost:5220
@token =CfDJ8JdJEervLchDnMkfpUArbPuZL-rNm2MmLh2sqzagk1coBIAgGrgOoRJ7ZFA4AY8YWyA-Uke9WOBi27v-c6Vee_cAcTPw8rdflFhfA1IAi0LAJwTceWUsggGTMZ5LkkPZm4TI3fqtJoUkttTElt3oq_sqaGTbDwtPyBRrxbjX0VwBvqEQMLtUVr7GhQ4o5BR84MvP86_Bx81Kc0FcNGoeiFBXBwRh0sS5Qk96H8iti7OPVe9qg9sBMTyK0Bma0I2BHhcqzOSA08xQ8ye-6z7fGirzcppkS-CYNuPZWgYZBqc4z3gNHLTGJmIfzIoEIziH_OTAa4ck01V1IF_HX6rFXWaN-MMNK8PYRzfR7psaM3QakCQ2cGwxgy9DUl00EyhQ_mpreQZO9QkRt8yIKNIkuFacvuKGSDr1zUx67HaklPPGg-PFOa9WVvrdFvaKSLmPyHSh7nALjEB-QdA39onFXPh8mrfweu-xxONdoHtD3PyuOVsj75N9ykfN4HI0xG7z2fBoBkxJzjzfFMOZ4H8E2ivbw9fKLHMKZzdbdoGp4cziI5KruLTP9MsiiEAyrPoF5pKuiGLZLkdaVomi16opsQ4SrV0O2ubRgN8Ny7pyDCLksSR8QI77Zhz8A613tU2KrwYjJrjaUroPVRkXOaqYsK5SP8iUPX_E76ZRdRuIqRKYqTCrqGmEMFkm_OsAchh02S33esdQMnBoNrxnqYsndgEIPJoKq1PgkqS47n-A_ZKcwapOTH4PC3zEHYZsCGzeMc3PASvCpLDtihdoN7UxxXY3tfyLN__urX9gAMu1llR1

GET {{RestaurantsAPI_HostAddress}}/api/restaurants
Authorization:Bearer{{token}}
###
GET {{RestaurantsAPI_HostAddress}}/api/restaurants/4

###
GET {{RestaurantsAPI_HostAddress}}/api/restaurants/3
Authorization:Bearer{{token}}

###
GET {{RestaurantsAPI_HostAddress}}/api/restaurants/123

###
POST {{RestaurantsAPI_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "Name": "Tasty Tests4",
  "Description": "A cozy restaurant serving a variety of delicious dishes.",
  "Category": "Indian",
  "HasDelivery": true,
  "ContactEmail": "info@tast.com",
  "ContactNumber": "555-1234",
  "City": "New York",
  "Street": "123 Main Street",
  "PostalCode": "10-010"
}
###

DELETE {{RestaurantsAPI_HostAddress}}/api/restaurants/1006
###

PATCH {{RestaurantsAPI_HostAddress}}/api/restaurants/8
Content-Type: application/json
{
  "Name": "Sample patch2",
  "Description": "This is a sample restaurant description.",
  "HasDelivery": true
}
###





POST {{RestaurantsAPI_HostAddress}}/api/restaurants/7/dishes
Content-Type: application/json
{
  "Name": "Spaghetti Bolognese",
  "Description": "Classic Italian pasta dish with rich meat sauce",
  "Price": 12.99,
  "KiloCalories": 750
}
###

GET {{RestaurantsAPI_HostAddress}}/api/restaurants/3/dishes
###

GET {{RestaurantsAPI_HostAddress}}/api/restaurants/3/dishes/3
###
DELETE {{RestaurantsAPI_HostAddress}}/api/restaurants/4/dishes
###






POST {{RestaurantsAPI_HostAddress}}/api/identity/register
Content-Type: application/json
{
    "email": "user@test.com",
    "password": "Password1!"
}
###
POST {{RestaurantsAPI_HostAddress}}/api/identity/login
Content-Type: application/json
{
    "email": "owner@test.com",
    "password": "Password1!"
}
###

PATCH {{RestaurantsAPI_HostAddress}}/api/identity/user
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "Nationality": "French",
  "DateOfBirth": "2010-01-01"
}
###