@RestaurantsAPI_HostAddress = https://localhost:7158
//http://localhost:5220
@token = CfDJ8JdJEervLchDnMkfpUArbPu_Dh8JU82GZrOpgq3JmwjsWnIIQmf6PPUg1LsNC6-L1_R19fsRRV6-oEheVopZ1TaFQoVkw8uGvnFUkLJ5bHVuF7-5Gn5pJXBeo3YO33P73gB6HwC2wcdVbIRgfuazXBQdXbnM2xHNO5LpCC3MLwi7Wyed-8pd7H2G_27bTZJgSO9s9Fd4tGkl1bF5f25xv4_Ct_ERzRDgmQvO39ifBumHsJaqEEmrPC2gqkSO8MO7_Rc2t_cUULuq3PE8E9PQI8FtvW3LXPPruVs2zmfbOxd0bG_HQ8OHTcxazsKONCdYkWM5wwYI0B5YqlRaSHpBPgyt9aSa_ZjnK5LPGkCcNGbtvNxiGfjnXZg6c6ucGTsczG-tLlVZrNUeD68tIFpd12Yyr8JcIDBtBBu7be7zb_H7rdBBmb_cvvZh9s86ex1KwIJbwOey8IC6V6JADmEHnBnUtHO1xC8PO0eGylN79gfZnhwBnJhUgjaGA7S6zPcwO5aLV0zMnoxKsNma6UW7X4I9G4lsoqAYkIB_2CrEcALBqbrPh9b2rX27EfGUKaOgpOhNFY74o5xLpcFhe1EUrh7ZIBqfe5qv1zN8fb--m4c_pLsLQUMjg3me-KuovrbH9eYVEssOfrmRAL1NmJvJJ6MiZroN0lVR__o7kAghlERx_S3E0zGZKTw1SWu0Uhx_F5CSxUxRR5yAguJ_8X-6nPnMDl6QzJ0fAzDoIGTEJNz2g_QSRU93zFSP8aAHmASDjn-OSIT5arSwnxYaJ5CpOep6rCf2CPz6i21_dr3t_kgyvreXO4TkVQMAmIhB9fTtFKExwiC7N5QJArXv9KfrFTf5pI_Btd87iduD5m-filyuDGQ80CJusLsvfPRdvf9K8g
GET {{RestaurantsAPI_HostAddress}}/api/restaurants
###
GET {{RestaurantsAPI_HostAddress}}/api/restaurants/4

###
GET {{RestaurantsAPI_HostAddress}}/api/restaurants/3
Authorization:Bearer{{token}}

###
GET {{RestaurantsAPI_HostAddress}}/api/restaurants/123

###
POST {{RestaurantsAPI_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "Name": "Tasty Tests4",
  "Description": "A cozy restaurant serving a variety of delicious dishes.",
  "Category": "Indian",
  "HasDelivery": true,
  "ContactEmail": "info@tast.com",
  "ContactNumber": "555-1234",
  "City": "New York",
  "Street": "123 Main Street",
  "PostalCode": "10-010"
}
###

DELETE {{RestaurantsAPI_HostAddress}}/api/restaurants/1006
###

PATCH {{RestaurantsAPI_HostAddress}}/api/restaurants/8
Content-Type: application/json
{
  "Name": "Sample patch2",
  "Description": "This is a sample restaurant description.",
  "HasDelivery": true
}
###





POST {{RestaurantsAPI_HostAddress}}/api/restaurants/7/dishes
Content-Type: application/json
{
  "Name": "Spaghetti Bolognese",
  "Description": "Classic Italian pasta dish with rich meat sauce",
  "Price": 12.99,
  "KiloCalories": 750
}
###

GET {{RestaurantsAPI_HostAddress}}/api/restaurants/3/dishes
###

GET {{RestaurantsAPI_HostAddress}}/api/restaurants/3/dishes/3
###
DELETE {{RestaurantsAPI_HostAddress}}/api/restaurants/4/dishes
###






POST {{RestaurantsAPI_HostAddress}}/api/identity/register
Content-Type: application/json
{
    "email": "user@test.com",
    "password": "Password1!"
}
###
POST {{RestaurantsAPI_HostAddress}}/api/identity/login
Content-Type: application/json
{
    "email": "testuser@test.com",
    "password": "Password1!"
}